<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CRUD_Sql_Server_y_Dataset</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DatosDS.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DatosDS.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DatosDS.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DatosDS.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>